# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Team Members

# Attribute name
nameFrom: name

# Model Class name
modelClass: Rebel59\Team\Models\Member

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
